//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LarkatorGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SaveFile {
            get {
                return ((string)(this["SaveFile"]));
            }
            set {
                this["SaveFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArkTools {
            get {
                return ((string)(this["ArkTools"]));
            }
            set {
                this["ArkTools"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputDir {
            get {
                return ((string)(this["OutputDir"]));
            }
            set {
                this["OutputDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int MaxLevel {
            get {
                return ((int)(this["MaxLevel"]));
            }
            set {
                this["MaxLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int LevelStep {
            get {
                return ((int)(this["LevelStep"]));
            }
            set {
                this["LevelStep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[ { \"Group\": \"Shopping List\", \"Order\": 0.0, \"Species\": \"Allosaurus\", \"MinLevel\":\n" +
            "                92, \"MaxLevel\": null, \"Female\": true }, { \"Group\": \"Worries\", \"O" +
            "rder\": 175.0, \"Species\": \"Alpha\n                Carnotaurus\", \"MinLevel\": 100, \"" +
            "MaxLevel\": null, \"Female\": null }, { \"Group\": \"Worries\", \"Order\": 50.0,\n        " +
            "        \"Species\": \"Alpha Leedsichthys\", \"MinLevel\": null, \"MaxLevel\": null, \"Fe" +
            "male\": null }, { \"Group\":\n                \"Worries\", \"Order\": 125.0, \"Species\": " +
            "\"Alpha Megalodon\", \"MinLevel\": 100, \"MaxLevel\": null, \"Female\":\n                " +
            "null }, { \"Group\": \"Worries\", \"Order\": 192.1875, \"Species\": \"Alpha Mosasaur\", \"M" +
            "inLevel\": null,\n                \"MaxLevel\": null, \"Female\": null }, { \"Group\": \"" +
            "Worries\", \"Order\": 287.5, \"Species\": \"Alpha Raptor\",\n                \"MinLevel\":" +
            " 100, \"MaxLevel\": null, \"Female\": null }, { \"Group\": \"Worries\", \"Order\": 443.75," +
            " \"Species\":\n                \"Alpha T-Rex\", \"MinLevel\": 100, \"MaxLevel\": null, \"F" +
            "emale\": null }, { \"Group\": \"Worries\", \"Order\":\n                521.875, \"Species" +
            "\": \"Giganotosaurus\", \"MinLevel\": null, \"MaxLevel\": null, \"Female\": null }, { \"Gr" +
            "oup\":\n                \"Worries\", \"Order\": 610.9375, \"Species\": \"Titanosaur\", \"Mi" +
            "nLevel\": null, \"MaxLevel\": null, \"Female\":\n                null }, { \"Group\": \"S" +
            "hopping List\", \"Order\": 87.5, \"Species\": \"Baryonyx\", \"MinLevel\": 100, \"MaxLevel\"" +
            ":\n                null, \"Female\": null }, { \"Group\": \"Shopping List\", \"Order\": 2" +
            "00.0, \"Species\": \"Dire Bear\", \"MinLevel\":\n                100, \"MaxLevel\": null," +
            " \"Female\": null }, { \"Group\": \"Worries\", \"Order\": 292.1875, \"Species\": \"Diseased" +
            "\n                Leech\", \"MinLevel\": null, \"MaxLevel\": null, \"Female\": null }, {" +
            " \"Group\": \"Shopping List\", \"Order\":\n                300.0, \"Species\": \"Quetzal\"," +
            " \"MinLevel\": null, \"MaxLevel\": null, \"Female\": null }, { \"Group\": \"Shopping\n    " +
            "            List\", \"Order\": 419.921875, \"Species\": \"Rex\", \"MinLevel\": 100, \"MaxL" +
            "evel\": null, \"Female\": null }, {\n                \"Group\": \"Shopping List\", \"Orde" +
            "r\": 510.9375, \"Species\": \"Yutyrannus\", \"MinLevel\": 84, \"MaxLevel\": null,\n       " +
            "         \"Female\": null } ]\n            ")]
        public string SavedSearches {
            get {
                return ((string)(this["SavedSearches"]));
            }
            set {
                this["SavedSearches"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10000")]
        public double MainWindowLeft {
            get {
                return ((double)(this["MainWindowLeft"]));
            }
            set {
                this["MainWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-10000")]
        public double MainWindowTop {
            get {
                return ((double)(this["MainWindowTop"]));
            }
            set {
                this["MainWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1252")]
        public double MainWindowWidth {
            get {
                return ((double)(this["MainWindowWidth"]));
            }
            set {
                this["MainWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public double MainWindowHeight {
            get {
                return ((double)(this["MainWindowHeight"]));
            }
            set {
                this["MainWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public int ConvertDelay {
            get {
                return ((int)(this["ConvertDelay"]));
            }
            set {
                this["ConvertDelay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int ListFontSize {
            get {
                return ((int)(this["ListFontSize"]));
            }
            set {
                this["ListFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double PinScale {
            get {
                return ((double)(this["PinScale"]));
            }
            set {
                this["PinScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1500")]
        public int TeleportHeightOffset {
            get {
                return ((int)(this["TeleportHeightOffset"]));
            }
            set {
                this["TeleportHeightOffset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TeleportFly {
            get {
                return ((bool)(this["TeleportFly"]));
            }
            set {
                this["TeleportFly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TeleportGhost {
            get {
                return ((bool)(this["TeleportGhost"]));
            }
            set {
                this["TeleportGhost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHealth {
            get {
                return ((bool)(this["ShowHealth"]));
            }
            set {
                this["ShowHealth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowStam {
            get {
                return ((bool)(this["ShowStam"]));
            }
            set {
                this["ShowStam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowOxygen {
            get {
                return ((bool)(this["ShowOxygen"]));
            }
            set {
                this["ShowOxygen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowFood {
            get {
                return ((bool)(this["ShowFood"]));
            }
            set {
                this["ShowFood"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowWeight {
            get {
                return ((bool)(this["ShowWeight"]));
            }
            set {
                this["ShowWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMelee {
            get {
                return ((bool)(this["ShowMelee"]));
            }
            set {
                this["ShowMelee"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowSpeed {
            get {
                return ((bool)(this["ShowSpeed"]));
            }
            set {
                this["ShowSpeed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shopping List")]
        public string LastGroup {
            get {
                return ((string)(this["LastGroup"]));
            }
            set {
                this["LastGroup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HideUntameable {
            get {
                return ((bool)(this["HideUntameable"]));
            }
            set {
                this["HideUntameable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GroupSearch {
            get {
                return ((bool)(this["GroupSearch"]));
            }
            set {
                this["GroupSearch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseSftp {
            get {
                return ((bool)(this["UseSftp"]));
            }
            set {
                this["UseSftp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SftpHost {
            get {
                return ((string)(this["SftpHost"]));
            }
            set {
                this["SftpHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int SftpPort {
            get {
                return ((int)(this["SftpPort"]));
            }
            set {
                this["SftpPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SftpUsername {
            get {
                return ((string)(this["SftpUsername"]));
            }
            set {
                this["SftpUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SftpPassword {
            get {
                return ((string)(this["SftpPassword"]));
            }
            set {
                this["SftpPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SftpRemotePath {
            get {
                return ((string)(this["SftpRemotePath"]));
            }
            set {
                this["SftpRemotePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoReload {
            get {
                return ((bool)(this["AutoReload"]));
            }
            set {
                this["AutoReload"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UsePrivateKey {
            get {
                return ((bool)(this["UsePrivateKey"]));
            }
            set {
                this["UsePrivateKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrivateKeyPath {
            get {
                return ((string)(this["PrivateKeyPath"]));
            }
            set {
                this["PrivateKeyPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PrivateKeyPassphrase {
            get {
                return ((string)(this["PrivateKeyPassphrase"]));
            }
            set {
                this["PrivateKeyPassphrase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[]")]
        public string SftpServerProfiles {
            get {
                return ((string)(this["SftpServerProfiles"]));
            }
            set {
                this["SftpServerProfiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SelectedServerProfile {
            get {
                return ((string)(this["SelectedServerProfile"]));
            }
            set {
                this["SelectedServerProfile"] = value;
            }
        }
    }
}
